---
# tasks file for deploy
- name: Create workdir
  command: "mkdir /tmp/app"

- name: Example clone repository
  git:
    repo: https://github.com/vinayakrj/java-war-project.git
    dest: /tmp/app

- name: Move in workdir
  become: yes
  shell: "cd /tmp/app && mvn package && cd /tmp/app/target"

- name: Copy files app in prod
  synchronize:
    src: /tmp/app/target
    dest: /usr/local/tomcat/webapps
    delegate_to: prod