---
# tasks file for deploy
- name: Create workdir
  command: "mkdir /tmp/app"

- name: Example clone repository
  git:
    repo: https://github.com/vinayakrj/java-war-project.git
    dest: /tmp/app

- name: Move in workdir
  become: yes
  shell: "cd /tmp/app && mvn package && cd /tmp/app/target"

- name: Copy war-file in master
  fetch: src=/tmp/app/target/my-app.war dest=/tmp/myapp_ans/my-app.war