---
# tasks file for common

- name: update packages
  become: yes
  apt:
    update_cache: yes

- name: install packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - tree
    - mc
    - htop
    - net-tools
    - git
    - maven
    - rsync